#pragma once

#define ROOT_PATH "C:\\Users\\mialb\\Downloads\\Hyperion\\"

#define MAX_TRANSFORMS 8192
#define TRANSFORM_HIERARCHY_WORK_GROUP_SIZE 256

#define MAX_BONES 256
#define BONE_HIERARCHY_WORK_GROUP_SIZE 64

#define ANIMATION_DESCRIPTOR_POOL_SIZE 8192
#define ENTITY_DESCRIPTOR_POOL_SIZE 8192

#define MAX_TEXT_VERTICES 65535
#define MAX_INTERFACE_VERTICES 65535
#define MAX_DEBUG_VERTICES 65535